version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app           # Code vom Host
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev
