name: News Agent

on:
  workflow_dispatch:
    inputs:
      dry:
        description: 'Dry run'
        required: false
        default: 'true'
      force:
        description: 'Force run (ignore schedule)'
        required: false
        default: 'true'

  schedule:
  - cron: '10 8,13,16 * * 1-5'  # z.B. Mo–Fr 06:10/10:10/15:10 UTC

concurrency:
  group: news-agent
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}                
      CRON_SECRET: ${{ secrets.NEWS_AGENT_CRON_SECRET }}
      DRY: ${{ inputs.dry }}
      FORCE: ${{ inputs.force }}

    steps:
      - name: Compose request URL (with optional flags)
        id: vars
        shell: bash
        run: |
          set -euo pipefail
          base="${BASE_URL%/}"
          path="/api/admin/news-agent/run"
          qs=""
          [ "${DRY:-}"   = "true" ] && qs="${qs:+$qs&}dry=1"
          [ "${FORCE:-}" = "true" ] && qs="${qs:+$qs&}force=1"
          url="$base$path"; [ -n "$qs" ] && url="$url?$qs"
          echo "url=$url" >> "$GITHUB_OUTPUT"
          echo "POST $url"

      - name: Call run endpoint
        shell: bash
        run: |
          set -euo pipefail
          url="${{ steps.vars.outputs.url }}"
          code=$(curl -sS -o /tmp/resp.json -w "%{http_code}" -X POST \
            -H "Accept: application/json" \
            -H "X-Cron-Auth: ${CRON_SECRET}" \
            "$url")
          echo "HTTP $code"
          echo "---- Response ----"
          cat /tmp/resp.json || true
          echo "------------------"
          if [ "$code" -lt 200 ] || [ "$code" -ge 300 ]; then
            exit 1
          fi

      - name: Show X-Route-Version header (diagnostics)
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          url="${{ steps.vars.outputs.url }}"
          curl -sSI -X POST \
            -H "X-Cron-Auth: ${CRON_SECRET}" \
            "$url" | grep -i '^X-Route-Version:' || true

