name: News Agent

on:
  workflow_dispatch:
    inputs:
      dry:
        description: "Dry run (nur Vorschau, keine DB-Einträge)"
        type: boolean
        default: true
        required: true
      force:
        description: "Zeiten ignorieren (jetzt ausführen)"
        type: boolean
        default: true
        required: true
  schedule:
    # Beispiel: jeden Tag 07:05 UTC
    - cron: "5 7 * * *"

jobs:
  run-agent:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.NEWS_AGENT_BASE_URL }}
      CRON_SECRET: ${{ secrets.NEWS_AGENT_CRON_SECRET }}
      INPUT_DRY: ${{ github.event.inputs.dry }}
      INPUT_FORCE: ${{ github.event.inputs.force }}
    steps:
      - name: Validate env
        run: |
          if [ -z "$BASE_URL" ]; then
            echo "ERROR: NEWS_AGENT_BASE_URL secret fehlt."
            exit 1
          fi
          if [ -z "$CRON_SECRET" ]; then
            echo "ERROR: NEWS_AGENT_CRON_SECRET secret fehlt."
            exit 1
          fi

      - name: Build URL
        id: build
        shell: bash
        run: |
          PATHNAME="/api/admin/news-agent/run"
          QS=""
          # inputs können bei schedule leer sein → als "false" behandeln
          DRY="${INPUT_DRY:-false}"
          FORCE="${INPUT_FORCE:-false}"

          if [ "$DRY" = "true" ]; then
            QS="?dry=1"
          fi
          if [ "$FORCE" = "true" ]; then
            if [ -z "$QS" ]; then
              QS="?force=1"
            else
              QS="$QS&force=1"
            fi
          fi

          URL="${BASE_URL}${PATHNAME}${QS}"
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "Calling: ${BASE_URL}${PATHNAME} (Query: ${QS:-<none>})"

      - name: Call News Agent (manual/cron)
        shell: bash
        run: |
          set -euo pipefail
          URL="${{ steps.build.outputs.url }}"
          # Header-Name MUSS zu deinem isCronAuthorized() passen (siehe Punkt 4)
          RESP_FILE="/tmp/resp.json"
          http_code=$(curl -sS -o "$RESP_FILE" -w "%{http_code}" -X POST \
            -H "X-Cron-Auth: ${CRON_SECRET}" \
            -H "Accept: application/json" \
            "$URL")

          echo "HTTP $http_code"
          echo "---- Response ----"
          cat "$RESP_FILE" || true
          echo "------------------"

          if [ "$http_code" -lt 200 ] || [ "$http_code" -ge 300 ]; then
            echo "Request failed (HTTP $http_code)"
            exit 1
          fi
