name: News Agent

on:
  workflow_dispatch:
    inputs:
      dry:
        description: "Dry run (nur Vorschau)"
        required: false
        default: "false"
      force:
        description: "Force run (Zeitfenster ignorieren)"
        required: false
        default: "false"

  
  schedule:
    - cron: "0 7,15 * * *"

concurrency:
  group: news-agent
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}                   
      CRON_SECRET: ${{ secrets.NEWS_AGENT_CRON_SECRET }}  
      DRY: ${{ inputs.dry }}
      FORCE: ${{ inputs.force }}

    steps:
      - name: Compose request URL (event-aware flags)
        id: vars
        shell: bash
        run: |
          set -euo pipefail
          base="${BASE_URL%/}"
          path="/api/admin/news-agent/run"

          # Flags nur bei manueller Ausführung respektieren.
          qs=""
          if [ "${GITHUB_EVENT_NAME}" = "workflow_dispatch" ]; then
            [ "${DRY:-}"   = "true" ] && qs="${qs:+$qs&}dry=1"
            [ "${FORCE:-}" = "true" ] && qs="${qs:+$qs&}force=1"
          fi

          url="$base$path"; [ -n "$qs" ] && url="$url?$qs"
          echo "url=$url" >> "$GITHUB_OUTPUT"
          echo "POST $url"

      - name: Call run endpoint
        shell: bash
        run: |
          set -euo pipefail
          url="${{ steps.vars.outputs.url }}"
          # -L folgt evtl. 308/307 Redirects von Vercel
          code=$(curl -sS -L -o /tmp/resp.json -w "%{http_code}" -X POST \
            -H "Accept: application/json" \
            -H "X-Cron-Auth: ${CRON_SECRET}" \
            "$url")
          echo "HTTP $code"
          echo "---- Response ----"
          cat /tmp/resp.json || true
          echo "------------------"
          # 2xx = ok (auch wenn 'skipped: not due' zurückkommt)
          test "$code" -ge 200 -a "$code" -lt 300

      - name: Show X-Route-Version header (diagnostics)
        if: always()
        shell: bash
        run: |
          set -euo pipefail
          url="${{ steps.vars.outputs.url }}"
          curl -sSI -L -X POST \
            -H "X-Cron-Auth: ${CRON_SECRET}" \
            "$url" | grep -i '^X-Route-Version:' || true