name: News Agent

on:
  workflow_dispatch:
    inputs:
      dry:
        description: 'Dry run?'
        required: true
        default: 'true'
      force:
        description: 'Force run?'
        required: true
        default: 'true'

env:
  BASE_URL: https://news-check-puce.vercel.app   # keine trailing slash

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Run agent
        env:
          NEWS_AGENT_CRON_SECRET: ${{ secrets.NEWS_AGENT_CRON_SECRET }}
          DRY: ${{ inputs.dry }}
          FORCE: ${{ inputs.force }}
        run: |
          set -euo pipefail
          # URL sauber zusammenbauen – EIN leading slash, kein doppelter //
          URL="${BASE_URL}/api/admin/news-agent/run?dry=${DRY:+1}&force=${FORCE:+1}"

          # Optional: zum Debuggen kannst du zusätzlich ?key=... anhängen
          # URL="${URL}&key=${NEWS_AGENT_CRON_SECRET}"

          RESP_FILE="$(mktemp)"
          http_code=$(curl -sS -o "$RESP_FILE" -w "%{http_code}" -X POST \
            -H "X-Cron-Auth: ${NEWS_AGENT_CRON_SECRET}" \
            -H "Authorization: Bearer ${NEWS_AGENT_CRON_SECRET}" \
            -H "Accept: application/json" \
            "$URL")

          echo "HTTP $http_code"
          echo "---- Response ----"
          cat "$RESP_FILE" || true
          echo "------------------"

          if [ "$http_code" -lt 200 ] || [ "$http_code" -ge 300 ]; then
            echo "Request failed (HTTP $http_code)"
            exit 1
          fi
