name: News Agent
on:
  workflow_dispatch:
    inputs:
      dry:
        description: 'Dry run'
        default: 'true'
      force:
        description: 'Force'
        default: 'true'
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}            # z.B. https://news-check-puce.vercel.app
      CRON_SECRET: ${{ secrets.NEWS_AGENT_CRON_SECRET }}
      DRY: ${{ inputs.dry }}
      FORCE: ${{ inputs.force }}
    steps:
      - name: Run agent
        shell: bash
        run: |
          set -euo pipefail
          URL="${BASE_URL%/}/api/admin/news-agent/run?dry=${DRY:+1}&force=${FORCE:+1}&key=${CRON_SECRET}"
          echo "POST $URL"
          http_code=$(curl -sS -o /tmp/resp.json -w "%{http_code}" -X POST \
            -H "Accept: application/json" \
            "$URL")
          echo "HTTP $http_code"
          echo "---- Response ----"
          cat /tmp/resp.json || true
          echo "------------------"
          test "$http_code" -ge 200 -a "$http_code" -lt 300
