name: News Agent Cron

on:
  schedule:
    - cron: "0 8,12,17 * * *"   # UTC-Zeiten, nach Bedarf anpassen
  workflow_dispatch: {}

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Call API
        run: |
          curl -sS -X POST "${{ secrets.PROD_URL }}/api/admin/news-agent/run" \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}" \
            --fail
